### ISSUE TITLE
Correção Exercício 3.13.1

### ISSUE THREAD

**Issue by mathiasgheno** [LeonardoRenoldi/3.13.1#1]
# Correção

> Faça o layout do wireframe abaixo usando flexbox.

![image](https://user-images.githubusercontent.com/14915619/183270648-7ccf3be1-ba00-4792-801e-b6e1af26e811.png)

Sua modal está centralizada verticalmente porém não está centralizada horizontalmente. Você poderia obter esse resultado aplicado o estilo de `container` dentro do seu `root`. Além disso, você precisa dizer para o browser que o root, que encapusa toda a sua modal, vai ocupar toda a altura disponível. Essa abordagem funciona pois agora você pode fazer uso de todo o espaço disponível de altura para alinhar o seu conteúdo verticalmente através do uso do `align-items`.

```css
.root {
    height: 100%;
    display: flex;
    justify-content: center;
    align-items: center;
}
```

**Nota:** 6 

# Comentários

Seria mais adequado remover as propriedades css de `width` para `.botaoVoltar` e `.Excluir`. Assim seu botão não irá quebrar o conteúdo do texto para uma nova linha.
